### ISSUE TITLE
Can't create any thumbnail of new video.

### ISSUE THREAD

**Issue by lsvf0240** [AlexPresso/VideoStation-FFMPEG-Patcher#114]
The videoStation can not create any thumbnail of new input videos,after patched.
How can I uninstall this patcher or salute this problem.thanks!

**Comment by AlexPresso** [comment]
Hi,
Please follow the issue template when posting a bug and give me the output of the `issue-report` script. I can't help you without these informations.
https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by AlexPresso** [comment]
Hi,
I recently fixed a permission issue when the ffmpeg wrapper tried to load utils scripts (used to fix ffmpeg arguments generated by VideoStation), could you please give it a try to check if your problem is solved ?

https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/releases/tag/3.0

**Comment by AlexPresso** [comment]
Hi,
after doing some tests in SynoPhoto, I was able to reproduce the issue. In fact, the thumbnail generation is working but is extremely slow. I decided to change the execution order to make ffmpeg first try to run the default passed args (instead of edited args). It will make it work back at usual.
