### ISSUE TITLE
[BUG] Specific video will not play

### ISSUE THREAD

**Issue by ner00** [AlexPresso/VideoStation-FFMPEG-Patcher#127]
I tried patching FFmpeg 4 and also FFmpeg 6, they both fail to play this particular video. Just for additional context, I tried that other wrapper and the playback for this same video does work with that one, but not with your wrapper. I think the details gathered by your reporting tool should tell you why that is the case, I'm up for testing if needed.

**Provide System Details**
- Report tool log: [VideoStation-FFMPEG-Patcher_issue_report_20240510_015716.log](https://gist.githubusercontent.com/ner00/6624c7cb0423ed1c5c110bbb9251fa26/raw/3b42ed2182eebaced50f0bc5641bc4e3075097d7/VideoStation-FFMPEG-Patcher_issue_report_20240510_015716.log)

**Describe the bug**
The playback never starts, from the report ffmpeg seems to quit early on.

**Additional context**
Most videos play, but a few like this one don't.

**Comment by AlexPresso** [comment]
Hi ner00,
Thanks for the report, I'll check it out as soon as I have time :)

**Comment by AlexPresso** [comment]
Hi,

The fix is ready, it was already validated with ner0, but for anyone who wants to give it a try just to make sure we don't have any regression, it would be highly appreciated. 

To do so, you can unpatch your current installation:
- `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -a unpatch`
And patch using the fixed wrapper:
- `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -a patch -b fix_vaapi`

Thank you very much to everyone

**Comment by AlexPresso** [comment]
Hi @fabian,
Hope you're doing well, sorry to disturb you but by any chance would you have a bit of time to test this patch please ?

**Comment by Fabian1601** [comment]
Hello Alex,
I'll try out the script tonight ;)

**Comment by Fabian1601** [comment]
Hello Alex,

Now I have more time :-)
I'm fine, hope you are too!
Whenever you do an update of the script I try this out too ;-)
I haven't noticed any negative effects with the current fix. 
All videos play and offline transcoding also works. 

But my girlfriend found another bug (nothing to do with this one). This one has probably been around for a long time and I suspect it's not related to your script, but maybe you see more than I do ;-)
When I have all the information together I will create a new report. 

Greetings
