### ISSUE TITLE
patcher won't work

### ISSUE THREAD

**Issue by dantin-github** [AlexPresso/VideoStation-FFMPEG-Patcher#13]
**System details**
- Synology model: 220+
- DSM version:7.0
- VideoStation version: 3.0.1-2067
- Advanced Media Extensions version: 1.1.1-0202
**Describe the bug**
after execute the Basic command, these shows:

bash: line 1: syntax error near unexpected token `newline'. along with the "DOCTYPE html" error

the patcher won't work.

**FFMPEG logs**
[use ssh to open logs in `/tmp/ffmpeg.log` then put the content in a code block / create a [gist](https://gist.github.com/)]

**Additional context**

**Comment by AlexPresso** [comment]
This error means you are fetching a webpage instead of the "raw" patch content.
This may be related to one of the following:
- Copy-pasted with a missing character
- Github having an issue serving the raw file (go on this page to check if you get the file content: https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh)

**Comment by AlexPresso** [comment]
I'm closing this issue because there was no further informations on the related problem.
Feel free to re-open it / open a new one if you need to.
