### ISSUE TITLE
hevc main 10 offline transcode to high fails

### ISSUE THREAD

**Issue by Fabian1601** [AlexPresso/VideoStation-FFMPEG-Patcher#16]
hello alex,

when i try to transcode hevc main 10 offline the conversion always fails and it creates me a 0mb mp4 file.
in the "offline transcoding list" it says "done".
but if i choose "medium" as resolution it creates the correct file.
are you already aware of the error?

greetings 

I have attached the log file from the conversion of the film in high and medium resolution
[ffmpeg.log](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/files/7520856/ffmpeg.log)
gs

**Comment by AlexPresso** [comment]
Hello Fabian,

Yes, I'm aware of an issue related to HEVC transcoding (even real-time transcoding), it's not directly related to the patcher (it's related to the wrapper), but I'm planning to fix it when I have time.

Could you put the content of your log file in a gist instead of a file please ?

Greetings

**Comment by Fabian1601** [comment]
hello alex,

here as gist.

https://gist.github.com/Fabian1601/e24a8695891a1d695dde9e90862227ed

greetings

**Comment by AlexPresso** [comment]
Hi,

Thank you for the logs, it will help me fix the wrapper and make it capable of wrapping Advanced Media Extensions.
I'll need some time to do it, but I'll keep the following issue opened and mention it in a future pull request.

Greetings

**Comment by pacifikballa** [comment]
AlexPresso,

Here is the link.  Its only good for 2 hours, so depending on your internet speeds, u should be good.  I have gigabit fiber.

http://gofile.me/6OElE/a0qvKsHty

**Comment by AlexPresso** [comment]
Thank you for the link, you said earlier:
> Maybe I can upload my patched file or wrapper so u can compare? I've never done that before though so wouldn't know where to start.

Do you mean you edited the wrapper downloaded by the script (`/var/packages/VideoStation/target/bin/ffmpeg`) ?

**Comment by pacifikballa** [comment]
> Thank you for the link, you said earlier:
> 
> > Maybe I can upload my patched file or wrapper so u can compare? I've never done that before though so wouldn't know where to start.
> 
> Do you mean you edited the wrapper downloaded by the script (`/var/packages/VideoStation/target/bin/ffmpeg`) ?

I didn't edit anything.  Just figured since it is all working for me, somehow mine may differ from yours.

**Comment by AlexPresso** [comment]
Oh okay, I understand
No the patch procedure is the same for everyone, my script is downloading the wrapper directly from [source](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/blob/main/ffmpeg-wrapper.sh) ;)

**Comment by pacifikballa** [comment]
> Oh okay, I understand No the patch procedure is the same for everyone, my script is downloading the wrapper directly from [source](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/blob/main/ffmpeg-wrapper.sh), without editing it ;)

Ok gotcha.....well, i'm not sure what i did, but everything i have is working...i tested it all.  HEVC with DTS/Atmos, EAC3, AAC, h264/h265...u name it, i got it, and it all works.  How did that download go?  Did the movie play for u?

**Comment by AlexPresso** [comment]
I was able to download the file but unfortunately it didn't play on my DS218Play, I'm still trying to understand why it fails

**Comment by pacifikballa** [comment]
All I remember doing was uninstalling Video Station, AME, and FFMPEG.

Then based on my logs, I installed them back in the following order:

1. Install FFMPEG
2. Install AME
3. Install Video Station
4. Stop Video Station, Start Video Station.

Then I tested all the different video files I had that had different audio
codecs and they all work.

Worth a shot to start clean and install in the order I did.  It may or may
not work for you, but it’s worth a shot.

**Comment by findstevehere** [comment]
so what should people do like myself do.....who arent that savvy with command line or terminal commands and there's two duelling people with two different methods of patching, with the seemingly more complicated, nebulas also seems to work better with H265, while Alex's, which I successfully did last time before the recent VS update because it's much simpler, but H265 doesnt seem to work consistently. I really wish someone would do a video or something, because these instructions are rarely complete....never gives you step by step instructions on every step and then others chime in about installing Putty or something and then just paste or use this command when, blah blah blah....it's nuts for regular people trying to wade through months and months, if not years of comments and trying to get a handle on the best route to go. thanks

**Comment by AlexPresso** [comment]
@findstevehere I think you sent this message to the wrong chan ;) this is the issue page of my patcher

**Comment by ja-vivanco** [comment]
In my case it fails when transcoding H265 in high quality AND using hardware transcoding. If you disable hardware transcoding it works with high and medium quality.

I have patched synocodec tool with https://github.com/dmc31a42/synocodectool-patch

**Comment by ja-vivanco** [comment]
You have to use Alex's script anyway, because even if hevec transcoding don't fully work, it still some quite common audio codecs that Videso Station native ffmepeg do not support, so my setup.

1) Install Video Station
2) Install community ffmpeg
1) use synocodectool patch and apply the path to the all of 3 suggested location.
2) use Alex Video Station patch

Option 1 Now, if you really need Hevc transcoding at high quality go to Video Station ->  configuration -> Advanced and disable transcoding. Obvisly you CPU needs to be good enough to process the transcoding without hardware acceleration

Option 2 Just select medium quality in the configuration of the app, DS video for your phone or TV.

**Comment by findstevehere** [comment]
> You have to use Alex's script anyway, because even if hevec transcoding don't fully work, it still some quite common audio codecs that Videso Station native ffmepeg do not support, so my setup.
> 
> 1. Install Video Station
> 2. Install community ffmpeg
> 3. use synocodectool patch and apply the path to the all of 3 suggested location.
> 4. use Alex Video Station patch
> 
> Option 1 Now, if you really need Hevc transcoding at high quality go to Video Station -> configuration -> Advanced and disable transcoding. Obvisly you CPU needs to be good enough to process the transcoding without hardware acceleration
> 
> Option 2 Just select medium quality in the configuration of the app, DS video for your phone or TV.

**Comment by findstevehere** [comment]
huh? Alex patch gets error - "error" install ffmpeg"  
what is synocodectool patch and 3 locations?

**Comment by AlexPresso** [comment]
@findstevehere could you run the following steps and send the output please:

- Connect to your NAS using SSH (admin user required) ([help](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/General_Setup/How_to_login_to_DSM_with_root_permission_via_SSH_Telnet))
- Use the command `sudo -i` to switch to root user
- `ls -al /var/packages`

**Comment by AlexPresso** [comment]
@findstevehere did you have the time to check my previous comment ?

**Comment by findstevehere** [comment]
hey thanks, will try later today and post.

**Comment by ja-vivanco** [comment]
> hey thanks, will try later today and post.



> huh? Alex patch gets error - "error" install ffmpeg" what is synocodectool patch and 3 locations?

Have you installed synocummunity ffmpeg before applying AlexPresso patch?

**Comment by AlexPresso** [comment]
@Fabian1601 Did you have the time to check if the problem is fixed by the CodecPack's patch ?

**Comment by Fabian1601** [comment]
Hello alex,

Give me a moment and I will test it.
Unfortunately, it takes me a few hours to re-index the videos after reinstalling VS (it also checks all the files again when it gets the database).
I will report as soon as it is ready

**Comment by Fabian1601** [comment]
So, I reset everything to original and ran your script over it.
Playback works great.
But offline transcoding aborts every time with "the network connection is unstable...".

**Comment by Fabian1601** [comment]
here the ffmpeg.log

https://gist.github.com/Fabian1601/ceda916cf53711f9a351fc9f1fe46bf4

**Comment by AlexPresso** [comment]
Moved to #36

**Comment by findstevehere** [comment]
> @findstevehere could you run the following steps and send the output please:
> 
> * Connect to your NAS using SSH (admin user required) ([help](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/General_Setup/How_to_login_to_DSM_with_root_permission_via_SSH_Telnet))
> * Use the command `sudo -i` to switch to root user
> * `ls -al /var/packages`

I get no such file or directory

MacBook-Air:~ root# ls -al /var/packages
ls: /var/packages: No such file or directory
MacBook-Air:~ root#

**Comment by findstevehere** [comment]
> > @findstevehere could you run the following steps and send the output please:
> > 
> > * Connect to your NAS using SSH (admin user required) ([help](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/General_Setup/How_to_login_to_DSM_with_root_permission_via_SSH_Telnet))
> > * Use the command `sudo -i` to switch to root user
> > * `ls -al /var/packages`
> 
> I get no such file or directory
> 
> MacBook-Air:~ root# ls -al /var/packages ls: /var/packages: No such file or directory MacBook-Air:~ root#

also not showing any ffmpeg log files at all or directory 

MacBook-Air:tmp root# ls -al | grep ffmpeg
MacBook-Air:tmp root# tail -200 ffmpeg.log
tail: ffmpeg.log: No such file or directory
MacBook-Air:tmp root#

**Comment by AlexPresso** [comment]
Please follow meticulously every step from this link: https://kb.synology.com/en-global/DSM/tutorial/How_to_login_to_DSM_with_root_permission_via_SSH_Telnet 

The reason it's not working is because you're executing the patch on your Mac (like you are trying to patch your mac). But it's not what you want to do. You want to patch your Synology NAS, and to do that, you need to connect to your NAS (through SSH) before executing the command to run the patch.
