### ISSUE TITLE
[BUG] transcode fails with "the network connection is unstable or the system is busy"

### ISSUE THREAD

**Issue by Fabian1601** [AlexPresso/VideoStation-FFMPEG-Patcher#6]
**System details**
- Synology model: ds1019+
- DSM version: 7.0-41882
- VideoStation version: 3.0.1-2067
- Advanced Media Extensions version: 1.1.0-0201
- ffmpeg version: 4.3.2-37

**Describe the bug**
after the script update, every conversion fails with "the network connection is unstable or the system is busy"
unfortunately no ffmpeg.log is created either.
have video station + advanced media extension + ffmpeg reinstalled several times but no change

**Comment by AlexPresso** [comment]
When you said in #4 that "the film is successfully converted" were you able to watch the video even with having the timecode staying on `-1 : -1 : -1` ?

**Comment by Fabian1601** [comment]
yes, he has successfully converted the film and I was able to play it or I could also watch all films (dts, true hd, etc.) in the browser.
it only shows -1: -1: -1 as the remaining time in the "Offline transcoding" window.
now nothing works.... 
Sorry if that wasn't clear before

**Comment by AlexPresso** [comment]
Don't worry ;)

Yes, then my last patch broke the decoding. 

To explain a bit:
that -1 -1 -1 bug is related to VideoStation trying to exchange timecode data with the Advanced Media Extensions `ffmpeg33` file, but since it's replaced by the `ffmpeg-wrapper`, the expected "data" isn't looking the same as if it were sent by the original `ffmpeg33`. 

What I tried to do with #5 was to wrap the `ffmpeg33` with the SynoComunity ffmpeg. I forced it on my DS218Play and it worked but unfortunately it doesn't on x64 architectures.

I'll have to take a closer look at both VideoStation's and Advanced Media Extensions source code. Synology now signs its spk (package archives) files with a PGP key, so I'll need a bit of time to do it.

In the meantime, I'll revert the last changes so you can decode the videos back again

**Comment by AlexPresso** [comment]
Closing this issue since it'll be related to #4 again
