### ISSUE TITLE
[QA] Hope to add support for FFMpeg 5 | FFMpeg 6

### ISSUE THREAD

**Issue by noir1216** [AlexPresso/VideoStation-FFMPEG-Patcher#68]

**Comment by AlexPresso** [comment]
For now it's not possible to add ffmpeg5 and ffmpeg6 support because these packages are missing some required Synology custom patches to handle VideoStation's custom parameters (i.e. `-hls_seek_time`).

If these patches are implemented to ffmpeg5 and ffmpeg6, I'll also improve the wrapper so it can handle these versions
