### ISSUE TITLE
[BUG] after last wrapper update video playback stops working

### ISSUE THREAD

**Issue by Fabian1601** [AlexPresso/VideoStation-FFMPEG-Patcher#77]
**System details**
- Synology model: ds1520+
- DSM version: 7.2-64570
- SynoCommunity FFMPEG Version: 4.4.4-49
- VideoStation version: 3.1.0-3153
- Advanced Media Extensions version: 1.1.0-51005
- 
**Describe the bug**
hello alex,
i ran the patch again today and now nothing works. neither the video playback nor the transcoding. no log file is created either. i can only give you the result of the patch

[result.txt](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/files/12209279/result.txt)

**Comment by FleXoft** [comment]
Same problem on 7.2 with: 

VideoStation-x86_64-3.1.0-3153.spk
MediaServer-x86_64-2.1.0-3304.spk
CodecPack-x86_64-3.1.0-3005.spk

No video playback!

**Comment by AlexPresso** [comment]
Hello @Fabian1601
Thank you for the logs, but could you post them into a gist please, the txt file appears to have wrong encoding

Hello @FleXoft 
Please also provide your patcher logs into a gist

**Comment by AlexPresso** [comment]
I also need the output of the following command: `cat /var/packages/VideoStation/target/bin/ffmpeg`

**Comment by FleXoft** [comment]
Mine seems to be Ok now after I reinstalled all the packages and the patch again, srry.

**Comment by AlexPresso** [comment]
No worries,
I think there was an issue with github at this moment, looks like the patcher logs from @Fabian1601 are giving plain HTML when requesting files instead of giving the raw file content

could you also try to repatch @Fabian1601

**Comment by Fabian1601** [comment]
just uninstalled and reinstalled all packages and ran the patch again, same result

this command cat /var/packages/VideoStation/target/bin/ffmpeg gives no result

https://gist.github.com/Fabian1601/227401271f22f0701e06e76bcba19a4b#file-gistfile1-txt

**Comment by AlexPresso** [comment]
> this command cat /var/packages/VideoStation/target/bin/ffmpeg gives no result

You say it's no result but I need you tell me the exact output of the command (result or not)

**Comment by AlexPresso** [comment]
Anyway, the "message of the day" is not displaying correctly in your situation, it's just like the Github raw file is not served, but you get HTML result.
So in my opinion, the same thing happens for the ffmpeg wrapper, instead of having a wrapper, you get an html file, which is incorrect and not allowing the content to play.

**Comment by AlexPresso** [comment]
I'm trying something just in case this is because of the github url scheme, please run the following :
- `sudo -i` (if not already root user)
- `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -a unpatch`
- `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/change_raw_base_url/patcher.sh | bash`

**Comment by Fabian1601** [comment]
looks good

https://gist.github.com/Fabian1601/f6ae101d7e4c005b353f78cff7e2c0ae
