### ISSUE TITLE
Video Station no more responding

### ISSUE THREAD

**Issue by Gustour** [AlexPresso/VideoStation-FFMPEG-Patcher#8]
Hello,
i run your script (without problem) then when i try to open video station it says, _"Unable to perform this operation, possibly because the network is unstable or the system is busy. Please try again later"_ and that never pass, even after rebooting the nas.
It used to work on DSM 6.x

RS819
DSM 7.0-41890
Video Station 3.0.1-2067
FFmpeg 4.3.2-37

I have to uninstall VS, and install it back to acces it again.

Do you have any ideas ?

Thanks (we can speak in french, i guess you are with your nickname)

**Comment by AlexPresso** [comment]
Hey there,

Thanks for the report. Yes, I'm aware of a bug with specific armv8 architecture, I'm going to fix it when I have some time.
Another user had the same issue ( #7 ) and gave some [infos](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/issues/7#issuecomment-880989822) on how he managed to resolve it, could you please try it and tell me if it solved your issue ?

PS: Yes, I do speak French but for documentation purposes (so everyone can read and understand) I prefer we keep this conversation in English.

**Comment by Gustour** [comment]
Ok it's working (dts, eac etc).
Just can't manage to watch my old sd movie (480p or lower, and mp3 as audio), is it normal ?

**Comment by AlexPresso** [comment]
No, it's not, mp3 + mpeg4 is supposed to be handled by default by VideoStation. 

It's probably due to previously patched files. You need to uninstall and reinstall VideoStation (there's an option to keep movies database) so you can clean the files patched by the `patcher.sh`.

Then you can re-run these steps to add the ffmpeg-wrapper.

**Comment by Gustour** [comment]
I tried a clean install (remove video station, ffmpeg, advance media extensio and serveur multimedia), add them all back, didn't patch anything, old movies (mpeg4/mp3) doesn't read.

In browser : "Le format video n'est pas pris en charge par mon ordinateur" (using chrome with vlc plugin)
In DS Video IOS : "Echec du transcodage. Le format de cette vidéo n'est pas pris en charge."

From a clean install, so it's nothing to do with your script (github), do you prefer/can help me by an other way (mail ?)

Thanks

**Comment by AlexPresso** [comment]
Oh ok, I thought decoding/transcoding was failing after you applied the patch. 
I have no idea why it doesn't work, were these movies playable before last VideoStation update ?

**Comment by Gustour** [comment]
From memories, yes. Do you want me to share one with you ?

**Comment by AlexPresso** [comment]
To be honest, it seems like it's related to VideoStation problem, I don't feel like I'll be able to fix the app itself. 
You may have more chances with the Synology support

**Comment by Gustour** [comment]
ok, so this is an other problem.

For the one of this case, following advises in issue 7 works, i can play dts in browser (video station), on mobile (ios, ds video), but not on tv (samsung, both ds video and dma doesn t work, i have video but no sounds, dts only, eac is ok)

**Comment by AlexPresso** [comment]
I'm facing the same issue with my Samsung TV (Tizen), for some reasons, Samsung stopped to pay for the DTS license a loooong time ago then Samsung TVs can't decode DTS anymore.

**Comment by Gustour** [comment]
I know, but why does the ffmpeg wrapper works for browser/mobile and not for tv ?

**Comment by AlexPresso** [comment]
That's because the wrapper "patches" the way VideoStation (and only VideoStation) is decoding/transcoding the media files.

When you're on the browser, you use VideoStation then the file is transcoded using the wrapper, when you use your mobile phone (DS Video) you're using VideoStation too and the media file is transcoded as well.

But when you're on a Samsung TV, if you use DLNA (Multimedia Server), there's no transcoding, the DLNA server is serving the plain file without transcoding (I mean I heard you can set it up for some codecs.) and by default Samsung TV doesn't support DTS at all.

The only way you could make it work on a Samsung TV would be to use a custom ffmpeg player (I don't know any for Tizen) or the "DS Video" app (not sure about the app name on Tizen) but as far as I know it has been completly abandoned and doesn't work anymore.
If you have furthermore questions, please contact the Samsung support.

Since we're leaving the main topic, I'm closing this issue for now. Feel free to reopen it / open a new one if you have another issue using the patch.
I've put a task on my to-do list to fix this issue when I have time.
